version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./sed.sh:/sed.sh
    command: "chmod +x /sed.sh && /sed.sh"
    ports:
      - 80:80